USE [TestDB]
GO
/****** Object:  Table [dbo].[INVENTARIOS]    Script Date: 1/20/2023 3:46:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INVENTARIOS](
	[CODIGO] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](250) NOT NULL,
	[DIRECCION] [nvarchar](250) NOT NULL,
	[SUCURSAL] [nvarchar](50) NOT NULL,
	[IDMONEDA] [int] NOT NULL,
	[fechacreacion] [date] NULL,
 CONSTRAINT [PK_INVENTARIO] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MONEDA]    Script Date: 1/20/2023 3:46:05 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MONEDA](
	[IDMONEDA] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPCION] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_MONEDA] PRIMARY KEY CLUSTERED 
(
	[IDMONEDA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[INVENTARIOS] ADD  DEFAULT (getdate()) FOR [fechacreacion]
GO
